# -*- coding: utf-8 -*-
"""Data manipulasi string 2 new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQMjWG-AfO1b8LRsp04PDFPM1XCqbhAe

Memotong String
"""

nama = 'Tio Rahellita Br Sihaloho'

print(nama[4])
print(nama[7])
print(nama[-1])
print(nama[-3])

"""Slicing String:"""

judul = 'Mata Kuliah Computer Programming 2'

print(judul[0:5])
print(judul[:10])
print(judul[10:15])
print(judul[-1:-3])
print(judul[:-3])
print(judul[-5:])

"""Memeriksa Karakter Akhir String
string.endswith()
"""

email_1 = 'rahellitarahel@gmail.com'
email_2 = 'rahellitarahel@outlook.com'

print(email_1.endswith('gmail.com'))  # True
print(email_2.endswith('gmail.com'))  # False

"""opersi in pada string"""

berita = 'Ramai-ramai developer di seluruh dunia mulai menggunakan \
teks editor masa kini seperti Visual Studio Code, \
atom, sublime text, dan lain sebagainya.'

print('sublime text' in berita)  # True
print('notepad++' in berita)     # False

"""Memeriksa Karakter Awal String
string.startswith()
"""

nomor_telepon_1 = '0871122334455'
nomor_telepon_2 = '6288776655300'
nomor_telepon_3 = '+6233003300330'

kode_negara = '+62'

print(nomor_telepon_1.startswith(kode_negara))  # False
print(nomor_telepon_2.startswith(kode_negara))  # False
print(nomor_telepon_3.startswith(kode_negara))  # True

"""Menghitung Panjang String"""

print(len('Indonesia'))  # output: 9
print(len('Malaysia'))   # output: 8