# -*- coding: utf-8 -*-
"""MANIPULASI DATA 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgeHlN0N_KeSZ2azt_IOH3I1zkPxrSmZ
"""

template = 'Halo, saya %s dari %s'

print(template %('Tio rahellita', 'indonesia'))

asal = 'rusia'

print(asal.find('rusiaaa'))

angka = '12345'
print('indeks angka 3:', angka.find('3'))
print('indeks angka 45:', angka.find('45'))
print('indeks angka 35:', angka.find('35'))

template = 'halo, saya {nama} dari {asal}'
template_2 = ' saya suka makan {} dan minum {}'

print(template.format(nama = 'Tio Rahellita', asal = 'Indonesia'))
print(template_2.format('Nasi Goreng', 'Air Putih'))

paragraf = 'baru baru ini telah ditemukan anomali di suatu sungai'
x = paragraf.count('di')

print(f'kata "di" muncul sebanyak {x} kali')

ibu_kota = 'jakarta'

print(ibu_kota.replace('a', 'i'))
print(ibu_kota.replace('kar', ''))
print(ibu_kota.replace('a',  ''))

print('indonesia adalah negara kepulauan'.swapcase())
print('aKu cInta Negeriku'.swapcase())

template = 'Halo, saya {nama} dari {asal}'
template_2 = 'Saya suka makan {} dan minum {}'

print(template.format(nama = 'tio rahellita sihaloho' asal = ))

print(' '.join(['aku', 'suka', 'python']))

print("halo selamat pagi".upper())
print("HALO APA KABAR".lower())

alamat ='surabaya, jawa, timur, indonesia'

print(alamat.split())
print(alamat.split(','))
print(alamat.split(', '))

nama = 'tio rahellita'
asal = 'indonesia'
print(f'perkenalan saya {nama} dari {asal}')