# -*- coding: utf-8 -*-
"""manipulasi data string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJ18TWVh13l9rQUgxwD3F2UhpvNSvPjz

nama: tio rahellita br sihalo
npm: 2451012021

STRING
"""

nama = 'tio rahellita br sihaloho'
asal ="indonesia"

print(nama)

print(asal)

print(nama + asal)

print("halo, nama saya",nama, "asal saya dari", asal)

data_lengkap = nama + asal

print(data_lengkap)

"""STRING + NON STRING"""

asal_kota = "Bandar Lampung"
kode_pos = 35144

asal_kota_kode_pos = asal_kota + str(kode_pos)

print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3

print(asal_kota_x3)