# -*- coding: utf-8 -*-
"""tipe data casting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uaQRo5nePlZcP2jSoeeLpqEKstddgTed

nama:tio rahellita br sihaloho
npm:2451012021

memeriksa jenis data
"""

nama = 'rahel'
usia = 20
lajang = True
print(type(nama))
print(type(usia))
print(type(lajang))

"""konversi tipe data"""

usia = input('Masukan usia anda')
print(type(usia))

a = 10/2
print(type(a))

kata = 'jeruk' * 5
print(type(kata))

panjang = int(input('masukkan panjang:'))
lebar = float(input('masukkan lebar:'))
print('Luas =', panjang * lebar)

nama = 'rahel'
tahun_lahir = 2006
print(nama +'lahir di tahun' + str(tahun_lahir))