# -*- coding: utf-8 -*-
"""TUGAS INDIVIDU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FvBdf-_pNFSveOGfY1J77dvn-B6jgJl
"""

# 1. DATA INPUT
data_kotor = "   #001-wahyu aji-informatika-python,java,php-aktif   "

# 2. PROSES PEMBERSIHAN (MANIPULASI STRING)

# a. Menghapus spasi di ujung dan karakter '#' di awal (strip & replace)
data_bersih = data_kotor.strip().replace('#', '')

# b. Memecah string menjadi list berdasarkan tanda pemisah '-' (split)
bagian = data_bersih.split('-')

id_pendaftar  = bagian[0]
nama_lengkap  = bagian[1].title()
program_studi = bagian[2].upper()
skill_raw     = bagian[3]
status_akun   = bagian[4].capitalize()

# c. Mengolah daftar skill (split & join)
skill_list   = skill_raw.split(',')
skill_tampil = ' & '.join(skill_list)

# d. Menghitung panjang ID dan jumlah skill (len & count)
panjang_id  = len(id_pendaftar)
total_skill = len(skill_list)

# 3. OUTPUT AKHIR (Menggunakan F-String & Escape Character)
print(f"Data Mentah: '{data_kotor}'")
print("=" * 38)
print(f"{'HASIL VERIFIKASI DATA':^38}")
print("=" * 38)
print(f"ID Pendaftar  : {id_pendaftar} ({panjang_id} digit)")
print(f"Nama Lengkap  : {nama_lengkap}")
print(f"Program Studi : {program_studi}")
print(f"Skill Dikuasai: {skill_tampil}")
print(f"Total Skill   : {total_skill}")
print(f"Status Akun   : {status_akun}")
print("=" * 38)